install:
- curl -sLo metaeditor.exe https://github.com/EA31337/FX-MT-VM/releases/download/4.x/metaeditor.exe
- git clone -q --recursive https://github.com/EA31337/EA31337-strategies ../include/EA31337-strategies
before_test:
- mklink /D "..\include\EA31337-classes" "%cd%"
- pwd
test_script:
- metaeditor /s /compile:. /inc:.. /log:errors.log || exit /b 0
- type *.log
- type *.log | find /v "Result" | findstr "error" && exit /b 1
- type *.log | find /v "Result" | findstr "warning" && exit /b 1
build: off
platform: x86
