---
name: Test

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '**.h'
      - '*.mq?'
      - '**.mq?'
      - '**/*.mq?'
      - '.github/workflows/test.yml'
  push:
    paths:
      - '**.h'
      - '*.mq?'
      - '**.mq?'
      - '**/*.mq?'
      - '.github/workflows/test.yml'

jobs:

  Compile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        uses: fx31337/mql-compile-action@master
        with:
          mt-version: 4.0.0.1349
          verbose: true
      - name: Print compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
        shell: powershell
      - name: Upload artifacts (MQL4)
        uses: actions/upload-artifact@v2
        with:
          name: files-ex4
          path: '**/*.ex4'
      - name: Upload artifacts (MQL5)
        uses: actions/upload-artifact@v2
        with:
          name: files-ex5
          path: '**/*.ex5'

  Experts-MQL4:
    defaults:
      run:
        shell: bash
        working-directory: tests
    needs: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - BufferStructTest
          - BufferTest
          - ChartTest
          - CompileIndicatorsTest
          - DatabaseTest
          - DrawIndicatorTest
          - EATest
          - IndicatorsTest
          - MailTest
          - MarketTest
          - MatrixTest
          - OrderTest
          - OrdersTest
          - StatsTest
          - StrategyTest
          - StrategyTest-RSI
          - SymbolInfoTest
          - SummaryReportTest
          - TickerTest
          - TradeTest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: files-ex4
      - name: Run ${{ matrix.test }}
        uses: fx31337/mql-tester-action@master
        with:
          BtDays: 4-12
          BtMonths: 1
          BtYears: 2021
          MtVersion: 4.0.0.1349
          TestExpert: ${{ matrix.test }}
          RunOnError: show_logs 200
    timeout-minutes: 10

  Scripts-MQL4:
    defaults:
      run:
        shell: bash
        working-directory: tests
    needs: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          #  - 3DTest
          - CollectionTest
          - ConfigTest
          - ConvertTest
          - DateTimeTest
          - DictTest
          - LogTest
          - MD5Test
          - MathTest
          - OrderQuery
          - ProfilerTest
          - RefsTest
          - TerminalTest
          - TimerTest
          - ValueStorageTest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: files-ex4
      - name: Run ${{ matrix.test }}
        uses: fx31337/mql-tester-action@master
        with:
          Script: ${{ matrix.test }}
    timeout-minutes: 10

  Scripts-MQL4-Ignore:
    defaults:
      run:
        shell: bash
        working-directory: tests
    needs: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          # @fixme: GH-266
          - RedisTest
          # @fixme: GH-266
          - WebTest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: files-ex4
      - name: Run ${{ matrix.test }}
        uses: fx31337/mql-tester-action@master
        with:
          Script: ${{ matrix.test }}
          RunOnFail: "exit 0"
    timeout-minutes: 10

  Trade-Tests-MQL4:
    defaults:
      run:
        shell: bash
        working-directory: Trade/tests
    needs: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - TradeSignalTest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: files-ex4
      - name: Run ${{ matrix.test }}
        uses: fx31337/mql-tester-action@master
        with:
          Script: ${{ matrix.test }}
    timeout-minutes: 10
